// <auto-generated />
namespace FreeBuy.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fristupdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fristupdates));
        
        string IMigrationMetadata.Id
        {
            get { return "202306260454319_fristupdates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
